TFM_SMC/OntoStats/views/gen_stats.py
from flask import render_template, Blueprint, send_file, redirect, url_for, request, session, flash
import os
import plotly.graph_objs as go
import json
import networkx as nx
from urllib.parse import urlparse
import subprocess

gen = Blueprint('gen', __name__)

@gen.route('/gen_stats', methods=('GET', 'POST'))
def gen_stats():
    purl = session.get('purl', None)

    if purl is None:
        # Manejar el caso en que no se encuentra la URL en la sesión
        return redirect(url_for('check.check_url'))

    with open('output.json') as f:
        data = json.load(f)
    
    # Crear el gráfico original
    fig = create_ontology_graph(data)
    graph_html = fig.to_html(full_html=False)

    ontology_title = data.get('ontologyTitle', None)

    metrics = ['axiomCount', 'declarationAxiomCount', 'classCount', 'objectPropertyCount', 'dataPropertyCount', 'individualCount', 'annotationPropertyCount', 'weight']
    graph_html2 = {}
    for metric in metrics:
        graph_html2[metric] = create_bar_chart(data, metric)

    # Cargar estadisticas.json y crear el gráfico de comparación si la sesión enriched está activa
    comparison_graph_html = None
    comparison_node_graph_html = None
    if session.get('enriched', False):
        with open('estadisticas.json') as f:
            stats_data = json.load(f)
        comparison_graph_html = create_comparison_chart(stats_data)
        comparison_node_graph = create_ontology_graph_with_comparison(data, stats_data)
        comparison_node_graph_html = comparison_node_graph.to_html(full_html=False)

    # Envía el archivo al cliente para descargarlo
    return render_template("gen_stats.html", graph_html=graph_html, graph_html2=graph_html2, comparison_graph_html=comparison_graph_html, comparison_node_graph_html=comparison_node_graph_html, ontology_title=ontology_title, purl=purl)


@gen.route('/download_json', methods=['GET'])
def download_json():
    # Obtener la ruta absoluta del archivo JSON
    root_dir = os.path.abspath(os.path.join(os.getcwd(), os.path.dirname(__file__), "..", ".."))
    json_filename = 'output.json'
    json_url = os.path.join(root_dir, json_filename)

    # Enviar el archivo JSON al cliente para descargarlo
    return send_file(json_url, as_attachment=True)

def get_final_part(url):
    parsed_url = urlparse(url)
    last_part = parsed_url.path.split('/')[-1]
    return last_part.replace('.owl', '')

def get_parent_ontology(url):
    parsed_url = urlparse(url)
    parts = parsed_url.path.split('/')
    try:
        index = parts.index('imports')
        parent = parts[index - 1]
        return parent
    except ValueError:
        return None

def create_ontology_graph(data):
    G = nx.DiGraph()
    original_ontology = data['idOntology']
    original_ontology_name = get_final_part(original_ontology)
    G.add_node(original_ontology_name)

    for entry in data['imports']:
        ontology_id = entry['idOntology']
        parent_ontology = get_parent_ontology(ontology_id)
        imported_ontology_name = get_final_part(ontology_id)
        G.add_node(imported_ontology_name)
        G.add_edge(parent_ontology if parent_ontology else imported_ontology_name, imported_ontology_name)
    
    axiom_counts = {get_final_part(entry['idOntology']): entry['ontologyMetrics']['axiomCount'] for entry in data['imports']}
    axiom_counts[original_ontology_name] = data['ontologyMetrics']['axiomCount']
    
    min_axiom_count = min(axiom_counts.values())
    max_axiom_count = max(axiom_counts.values())
    scaled_sizes = {node: 20 + (axiom_counts[node] - min_axiom_count) / (max_axiom_count - min_axiom_count) * 100 for node in axiom_counts}

    pos = nx.spring_layout(G)

    node_trace = go.Scatter(x=[], y=[], text=[], mode='markers+text', hoverinfo='text', marker=dict(size=[], color='LightSkyBlue'))
    edge_trace = go.Scatter(x=[], y=[], line=dict(width=1, color='#888'))

    for node in G.nodes():
        x, y = pos[node]
        node_trace['x'] += (x,)
        node_trace['y'] += (y,)
        
        if node == original_ontology_name:
            text = node
        else:
            parent_ontology = get_parent_ontology(f"http://example.com/imports/{node}.owl")
            if parent_ontology:
                text = f"{parent_ontology}/{node}"
            else:
                text = node

        node_trace['text'] += (text,)
        node_trace['marker']['size'] += (scaled_sizes[node],)

    for edge in G.edges():
        x0, y0 = pos[edge[0]]
        x1, y1 = pos[edge[1]]
        edge_trace['x'] += (x0, x1, None)
        edge_trace['y'] += (y0, y1, None)

    fig = go.Figure(data=[edge_trace, node_trace],
                    layout=go.Layout(
                        title='Ontology Graph',
                        titlefont_size=16,
                        showlegend=False,
                        hovermode='closest',
                        margin=dict(b=20,l=5,r=5,t=40),
                        xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
                        yaxis=dict(showgrid=False, zeroline=False, showticklabels=False))
                    )
    return fig

def create_bar_chart(data, metric_name):
    ontologies = data['imports']

    ontology_names = [get_final_part(ontology['idOntology']) for ontology in ontologies]
    parent_ontology_names = [get_parent_ontology(ontology['idOntology']) for ontology in ontologies]
    metric_values = [ontology['ontologyMetrics'][metric_name] for ontology in ontologies]

    original_ontology_name = get_final_part(data['idOntology'])
    parent_ontology_name = get_parent_ontology(data['idOntology'])
    original_metric_value = data['ontologyMetrics'][metric_name]

    ontology_names.insert(0, original_ontology_name)
    parent_ontology_names.insert(0, parent_ontology_name)
    metric_values.insert(0, original_metric_value)

    colors = ['red'] + ['blue' for _ in parent_ontology_names[1:]]

    trace = go.Bar(
        x=[f"{parent}|{ontology}" if parent else ontology for ontology, parent in zip(ontology_names, parent_ontology_names)],
        y=metric_values,
        marker=dict(color=colors)
    )

    layout = go.Layout(
        title=f'Comparacion de {metric_name}',
        xaxis=dict(title='Ontologies'),
        yaxis=dict(title=metric_name)
    )

    fig = go.Figure(data=[trace], layout=layout)
    graph_html = fig.to_html(full_html=False)

    return graph_html

def create_comparison_chart(data):
    methods = ['original', 'star', 'bot', 'top']
    metrics = {
        'NumeroDeAxiomas': ['NumeroDeAxiomasOriginal', 'AxiomasFinales_star', 'AxiomasFinales_bot', 'AxiomasFinales_top'],
        'ClasesFinales': ['NumeroDeClasesOriginal', 'ClasesFinales_star', 'ClasesFinales_bot', 'ClasesFinales_top'],
        'PesoMB': ['PesoOriginalMB', 'PesoResultadoStarMB', 'PesoResultadoBotMB', 'PesoResultadoTopMB']
    }

    figures = {}

    for metric_name, metric_keys in metrics.items():
        x_values = []
        y_values = []
        for method, key in zip(methods, metric_keys):
            # Verificar si la clave está presente en el JSON
            if key in data and data[key] != 0:
                x_values.append(method)
                y_values.append(data[key])

        if x_values and y_values:
            trace = go.Bar(
                x=x_values,
                y=y_values,
                marker=dict(color='blue')
            )
            layout = go.Layout(
                title=f'Comparacion de {metric_name}',
                xaxis=dict(title='Metodos'),
                yaxis=dict(title=metric_name)
            )
            fig = go.Figure(data=[trace], layout=layout)
            figures[metric_name] = fig.to_html(full_html=False)
    
    return figures

@gen.route('/back_to_main', methods=('GET',))
def back_to_main():
    session.pop('purl', None)
    session.pop('enriched', None)
    return redirect(url_for('index'))

@gen.route('/enrich_ontology', methods=['GET'])
def enrich_ontology():
    purl = session.get('purl', None)

    ontology_url_without_extension = os.path.splitext(purl)[0]

    jar_file = "OntoStats/static/prueba6.jar"
    output_dir = "salidas/"
    java_command = f"java --add-opens java.base/java.lang=ALL-UNNAMED -Xmx10G -jar {jar_file} -t 5 {ontology_url_without_extension} {output_dir} Star"

    try:
        subprocess.run(java_command, check=True, shell=True)
        session['enriched'] = True
    except subprocess.CalledProcessError:
        flash("Error al ejecutar el archivo JAR para enriquecer la ontología.")
    
    return redirect(url_for('gen.gen_stats'))


def create_ontology_graph_with_comparison(data, stats_data):
    G = nx.DiGraph()

    # Crear el nodo de la ontología original
    original_ontology = data['idOntology']
    original_ontology_name = get_final_part(original_ontology)
    G.add_node(original_ontology_name)

    # Agregar nodos de importaciones
    for entry in data['imports']:
        ontology_id = entry['idOntology']
        parent_ontology = get_parent_ontology(ontology_id)
        imported_ontology_name = get_final_part(ontology_id)
        G.add_node(imported_ontology_name)
        G.add_edge(parent_ontology if parent_ontology else original_ontology_name, imported_ontology_name)

    # Obtener el axiom count para cada nodo
    axiom_counts = {get_final_part(entry['idOntology']): entry['ontologyMetrics']['axiomCount'] for entry in data['imports']}
    axiom_counts[original_ontology_name] = data['ontologyMetrics']['axiomCount']

    # Escalar los tamaños del círculo entre un rango definido
    min_axiom_count = min(axiom_counts.values())
    max_axiom_count = max(axiom_counts.values())
    scaled_sizes = {node: 20 + (axiom_counts[node] - min_axiom_count) / (max_axiom_count - min_axiom_count) * 100 for node in axiom_counts}

    # Añadir el tamaño del círculo adicional basado en AxiomasFinales_star
    if 'AxiomasFinales_star' in stats_data:
        axiom_count_star = stats_data['AxiomasFinales_star']

TFM_SMC/OntoStats/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}{% endblock %} - OntoStats</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{{ url_for('static', filename='img/logo.png')}}">
    <!-- Enlaces de Bootstrap para el estilo -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- Archivo de estilos personalizado -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css')}}">
    <!-- Fuentes especiales -->
    <script src="https://kit.fontawesome.com/0ad327ab39.js" crossorigin="anonymous"></script>
    <!-- Javascript -->
    <script src="{{ url_for('static', filename='js/scripts.js')}}"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

</head>

<body>
    <div class="container-fluid">
        <div class="navb">
            <nav class="navbar navbar-expand-sm navbar-light bg-light border-1 border-bottom">
                <a class="navbar-brand" href="{{ url_for('gen.back_to_main') }}">
                    <img src="{{ url_for('static', filename='img/logo.png')}}" alt="Logo" width="50" height="50">
                    OntoStats
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#MenuNav">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="MenuNav" class="collapse navbar-collapse justify-content-end">
                    <ul class="navbar-nav ms-3">

                    </ul>
                </div>
            </nav>
            <div class="modal fade" id="logoutModal" tabindex="-1" aria-labelledby="logoutModalLabel"
                aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="logoutModalLabel">Cerrar sesión</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            ¿Está seguro de que desea cerrar sesión?
                        </div>
                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-secondary mb-4"
                                data-bs-dismiss="modal">Cancelar</button>
                            <a href="" class="btn btn-primary d-grid">Aceptar</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="content">
            {% block content %}{% endblock %}
        </div>

        <footer class="bg-secondary text-white py-2">
            <div class="container">
                <div class="row border-1 border-bottom">
                    <div class="col-lg-4 col-md-6 mb-5 mb-lg-0 text-center ">
                        <h6 class="text-uppercase mb-3">OntoStats</h6>
                        <p>Estudiante del Máster Universitario en Estadística Computacional y Ciencia de Datos para la Toma de Decisiones realizando el TFM
                        </p>
                        <ul class="list-inline mt-4">
                            <li class="list-inline-item"><a href="https://www.facebook.com/"
                                    class="text-decoration-none text-white"><i class="fab fa-facebook-f"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="https://www.twitter.com/"
                                    class="text-decoration-none text-white"><i class="fab fa-twitter"></i></a></li>
                            <li class="list-inline-item"><a href="https://www.instagram.com/"
                                    class="text-decoration-none text-white"><i class="fab fa-instagram"></i></a>
                            </li>
                            <li class="list-inline-item"><a href="https://www.linkedin.com/"
                                    class="text-decoration-none text-white"><i class="fab fa-linkedin-in"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-5 mb-lg-0 text-center">
                        <h6 class="text-uppercase mb-3">Enlaces rápidos</h6>
                        <ul class="list-unstyled mb-0">
                            <li><a href="{{ url_for('contacto')}}"
                                    class="text-decoration-none text-white">Contacto</a></li>
                            <li><a href="{{ url_for('quienes_somos')}}" class="text-decoration-none text-white">Quienes
                                    somos</a></li>
                            <li><a href="{{ url_for('politica_privacidad')}}"
                                    class="text-decoration-none text-white">Política de privacidad</a></li>
                            <li><a href="{{ url_for('terminos_condiciones')}}"
                                    class="text-decoration-none text-white">Términos y condiciones</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-5 mb-md-0 text-center">
                        <h6 class="text-uppercase mb-3">Información de contacto</h6>
                        <ul class="list-unstyled mb-0">
                            <li><i class="fas fa-map-marker-alt me-2"></i>Dirección de la empresa</li>
                            <li><i class="fas fa-phone-alt me-2"></i>Teléfono de la empresa</li>
                            <li><i class="fas fa-envelope me-2"></i>Correo electrónico de la empresa</li>
                        </ul>
                    </div>
                </div>
                <div class="row mt-0">
                    <div class="col-12 text-center">
                        <p class="mb-0">&copy; 2024 OntoStats. Todos los derechos reservados.</p>
                    </div>
                </div>
            </div>
        </footer>

        <!-- Enlaces de Bootstrap para los scripts -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous">
        </script>
    </div>
</body>

</html>

TFM_SMC/OntoStats/templates/gen_stats.html
{% extends "base.html" %}
{% block title %}Estadísticas generadas{% endblock %}
{% block content %}

<div class="container">
    <h1>Informe estadístico de {{ ontology_title }}</h1>
    <p>¡Haz clic en el botón para descargar el JSON!</p>
    <a href="{{ url_for('gen.download_json') }}"  class="btn btn-primary">Descargar JSON</a>
    <a href="{{ url_for('gen.enrich_ontology') }}"  class="btn btn-primary">Enriquecer ontología</a>
    <p>URL de la ontología: {{ purl }}</p>

    <h1>Ontology Hierarchy with Import Information</h1>
    <div id="graph">
        {{ graph_html|safe }}
    </div>

    <div>
        <h2>Ontology Metrics</h2>
        {% for metric, graph_html in graph_html2.items() %}
            <div>
                <h3>{{ metric }}</h3>
                {{ graph_html|safe }}
            </div>
        {% endfor %}
    </div>

    {% if comparison_graph_html %}
    <div>
        <h2>Comparison Charts</h2>
        {% for metric, graph_html in comparison_graph_html.items() %}
            <div>
                <h3>{{ metric }}</h3>
                {{ graph_html|safe }}
            </div>
        {% endfor %}
    </div>
    {% endif %}

    {% if comparison_node_graph_html %}
    <div>
        <h2>Ontology Graph with AxiomasFinales_star Comparison</h2>
        <div id="comparison-graph">
            {{ comparison_node_graph_html|safe }}
        </div>
    </div>
    {% endif %}
  
</div>

{% endblock %}

TFM_SMC/OntoStats/templates/principal.html
{% extends "base.html" %}
{% block title %}Menu principal{% endblock %}
{% block content %}

<div class="col-md-6 mx-auto">
    <form class="p-3 bg-light border-1 border primary shadow-lg" method="post" id="formulariol">
        <div class="center">
            <h1>¡Bienvenido a OntoStats!</h1>
            <p>Introduzca la url de la ontología a analizar.</p>
        </div>
        <div class="mb-3">
            <label for="url" class="form-label" >URL</label>
            <input type="text" class="form-control" id="purl" name="purl" placeholder="http://purl.obolibrary.org/obo/ejemplo.owl">
        </div>
        <div class="center">
            <button type="submit" class="btn btn-primary">Obtener estadísticas</button>
        </div>
    </form>
</div>

{% endblock %}